### ISSUE TITLE
Completion function file name wrong

### ISSUE THREAD

**Issue by kopischke** [laughedelic/pisces#2]
_fish_ lazy loading of functions needs a function file name matching the function name. _pisces_ tab override completion function is called `_pisces_complete` and mapped as such in user keybindings, but the containing file is `_pisces_tab.fish`, which will make the mapping spew errors on every _fish_ session but the initial one.

**Comment by laughedelic** [comment]
Good catch! Fixed in b4b415527a951925f8c3bf4bba151d5df4b7d837
