### ISSUE TITLE
Not working with Fisher 4

### ISSUE THREAD

**Issue by ngmoviedo** [laughedelic/pisces#27]
I've recently installed this plugin via Fisher. After many shell reloads and reinstalls I came to the conclusion that it was not working. On the other hand, when installed through omf I've have had no problem at all.
I haven't altered fisher's default configuration, and it has worked for all the other plugins I've used.
I'm using Arch Linux and Kitty as terminal emulator.
Congrats on this great plugin, anyway. I find it really useful and comfortable.

**Comment by ngmoviedo** [comment]
I can confirm that pull request #26 solves the issue for me.

**Comment by laughedelic** [comment]
hi @ngmoviedo! thanks for reporting and for validating that #26 fixes it 👍 
I'll reply there too.
