### ISSUE TITLE
Not working when fish_vi_key_bindings is set

### ISSUE THREAD

**Issue by ubmit** [laughedelic/pisces#29]
I've just installed the plugin using Fisher 4.1.0 and it simply doesn't work if `fish_vi_key_bindings` is set. It works perfectly when the default bindings are set, though. Is there any workaround?

**Comment by jorgebucaran** [comment]
@guilhermedeandrade Are you seeing any errors like "test: Missing argument at index 2"? If you are, then it could be that `$fish_key_bindings` is not set at the time this runs: 

https://github.com/laughedelic/pisces/blob/e45e0869855d089ba1e628b6248434b2dfa709c4/conf.d/pisces.fish#L1-L5

**Comment by ubmit** [comment]
I guess it is already set, because I have it in my `config.fish` file. Also:
<img width="313" alt="image" src="https://user-images.githubusercontent.com/8797405/102685855-61d62700-41db-11eb-9f01-b5e19a798070.png">

**Comment by jorgebucaran** [comment]
Could you describe what didn't work exactly? 

1. What did you do?
2. What actually happened?
3. What did you expect to happen?

**Comment by ubmit** [comment]
As I said, it simply doesn't work. Nothing. It doesn't throw any error either.

1. Installed the plugin using Fisher 4.1.0 and typed `(`, `[` and `"`, but nothing autocloses.
2. Nothing happened.
3. I expected it to autoclose.

**Comment by jorgebucaran** [comment]
@guilhermedeandrade What does `echo $fish_key_bindings` tell you?

**Comment by ubmit** [comment]
> @guilhermedeandrade What does `echo $fish_key_bindings` tell you?

https://github.com/laughedelic/pisces/issues/29#issuecomment-748447295

`fish_vi_key_bindings`

**Comment by jorgebucaran** [comment]
Could you try autopair.fish instead? I don't know what the problem could be with this plugin.

**Comment by ubmit** [comment]
Sure, will try it!

**Comment by ubmit** [comment]
`autopair.fish` doesn't work with `fish_vi_key_bindings` either

**Comment by jorgebucaran** [comment]
@guilhermedeandrade Does it work on a new tab?

**Comment by jorgebucaran** [comment]
@guilhermedeandrade Should be fixed now. 💯

**Comment by ubmit** [comment]
> @guilhermedeandrade Should be fixed now. 💯

It works perfectly, thank you 🙏
