### ISSUE TITLE
I am unable to fully uninstall pisces

### ISSUE THREAD

**Issue by ta3pks** [laughedelic/pisces#30]
I uninstalled the package using fisher however I still get completions How do i completely remove pisces from my shell

**Comment by jorgebucaran** [comment]
Pisces just have bindings, not shell completions. The code that should erase then on uninstall is here

https://github.com/laughedelic/pisces/blob/e45e0869855d089ba1e628b6248434b2dfa709c4/conf.d/pisces.fish#L23-L42

Not sure it completely removes all Pisces' state, to be honest. Does Pisces still work if you open another terminal tab?

**Comment by jorgebucaran** [comment]
Pisces just has bindings, not shell completions. The code that should erase then on uninstall is here

https://github.com/laughedelic/pisces/blob/e45e0869855d089ba1e628b6248434b2dfa709c4/conf.d/pisces.fish#L23-L42

Not sure it completely removes all Pisces' state, to be honest. Does Pisces still work if you open another terminal tab?

**Comment by jorgebucaran** [comment]
Pisces just has bindings, not shell completions. The code that should erase them on uninstall is here

https://github.com/laughedelic/pisces/blob/e45e0869855d089ba1e628b6248434b2dfa709c4/conf.d/pisces.fish#L23-L42

Not sure it completely removes all Pisces' state, to be honest. Does Pisces still work if you open another terminal tab?

**Comment by ta3pks** [comment]
I ended up doing `find . -iname \*pisces\* -exec rm {} +` and `find .  -exec sed '/pisces/d' {} -i'' \;` and restarted the terminal only then auto pairing stopped. For some reason after `fisher remove` conf.d/pisces.fish and all other pisces related files were still there.
I think this is a pisces related uninstall issue rather than fisher because all other uninstalls using fisher worked fine except for pisces
