### ISSUE TITLE
2.7?

### ISSUE THREAD

**Issue by tommyjcarpenter** [laughedelic/pisces#9]
The README says:

```
This plugin works best with fish v2.6, because it has a feature called bracketed (a.k.a safe) paste which solves the problem with pasting strings containing paired symbols (they get autoclosed), see #6 for details.
```

I am now on Fish 2.7. Will this plugin work in 2.7?

**Comment by laughedelic** [comment]
Yep! I'm using fish v2.7.1 and don't have any problems 👌 I will clarify the readme:

> This plugin works best with fish v2.6 _**(or later)**_
